
test : test.o
	./test.o blarg blirg
	./test.o aie eia
	./test.o longueur rueugnolo

test.o : ex18.c
	gcc -o test.o -Wall ex18.c


testarg : ex17
	./ex17 4.2 6.8

ex17 : ex17.c
	gcc -o ex17 -Wall ex17.c
	
clean :
	rm -f ex17
	ls -l
	

