
ex15 : compilation15
	./compilation15

compilation15 : ex15.c
	gcc -o compilation15 -Wall ex15.c


ex14 : compilation14
	./compilation14

compilation14 : ex14.c
	gcc -o compilation14 -Wall ex14.c


ex13 : compilation13
	./compilation13

compilation13 : ex13.c
	gcc -o compilation13 -Wall ex13.c


ex12 : compilation12
	./compilation12

compilation12 : ex12.c
	gcc -o compilation12 -Wall ex12.c


tab : compilation_tab
	./compilation_tab

compilation_tab : tab.c
	gcc -o compilation_tab -Wall tab.c

sizeof : compilation
	./compilation

compilation : sizeof.c
	gcc -o compilation -Wall sizeof.c
